#!/usr/bin/env bash
#author massard-t
set -euo pipefail
IFS=$'\n\t'

#/ Usage: crlib user/repository
#/ Description: Simple script allowing you to download a lib trough github
#/ Examples: crlib massard-t/libmy:1.0
#/ Options:
#/   --help: Display this help message
usage() { grep '^#/ ' "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage

readonly LOG_FILE="/tmp/$(basename "$0").log"
debug()    { echo "[DEBUG]    $*" | tee -a "$LOG_FILE" >&2 ; }
info()    { echo "[INFO]    $*" | tee -a "$LOG_FILE" >&2 ; }
warning() { echo "[WARNING] $*" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "[ERROR]   $*" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "[FATAL]   $*" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

tmp_dir=$(mktemp)

declare USERNAME
declare REPOSITORY
declare TAG
declare DOWNLOAD_URL
declare BASE_URL="https://github.com"


cleanup() {
    rm -rf $tmp_dir
    #rm -rf $TAG.tar.gz # Dev purpose
}


get_infos() {
        IFS='/:' read username repository tag <<< "$*"
        USERNAME="$username"
        REPOSITORY="$repository"
        TAG="${tag:-master}"
}

set_download_url() {
        DOWNLOAD_URL="$BASE_URL/$USERNAME/$REPOSITORY/archive/$TAG.tar.gz"
        info "Using download url: $DOWNLOAD_URL"
}

download_lib() {
        info "Downloading..."
        wget -P "$tmp_dir/" -q --progress=bar:force "$DOWNLOAD_URL"
        info "Done."
}

extract_lib() {
        tar xf $tmp_dir/$TAG.tar.gz -C "./"
        mv $REPOSITORY-$TAG "./$REPOSITORY"
}

main() {
        debug "Using temp directory: $tmp_dir"
        get_infos "$*"
        info "Username:         $USERNAME"
        info "Repository:       $REPOSITORY"
        info "Tag:              $TAG"
        set_download_url
        download_lib
        extract_lib
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]];
then
    trap cleanup EXIT
    [[ $# -eq 0 ]] && fatal "Please provide an argument using the following format: username/repository"
    main "$*"
fi
