#!/usr/bin/env bash
#author massard-t
set -euo pipefail
IFS=$'\n\t'

#/ Usage: crlib user/repository
#/ Description: Simple script allowing you to download a lib trough github
#/ Examples: crlib massard-t/libmy
#/ Options:
#/   --help: Display this help message
usage() { grep '^#/ ' "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage

readonly LOG_FILE="/tmp/$(basename "$0").log"
debug()    { echo "[DEBUG]    $*" | tee -a "$LOG_FILE" >&2 ; }
info()    { echo "[INFO]    $*" | tee -a "$LOG_FILE" >&2 ; }
warning() { echo "[WARNING] $*" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "[ERROR]   $*" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "[FATAL]   $*" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

tmp_dir=$(mktemp)

declare USERNAME
declare REPOSITORY
declare TAG


cleanup() {
    # Remove temporary files
    # Restart services
    # ...
    rm -rf $tmp_dir
}


get_repo() {
        IFS=/ read username repository <<< "$*"
        USERNAME="$username"
        REPOSITORY="$repository"
}


main() {
        debug "Using temp directory: $tmp_dir"
        get_repo "$*"
        info "Username:         $USERNAME"
        info "Repository:       $REPOSITORY"
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]];
then
    trap cleanup EXIT
    [[ $# -eq 0 ]] && fatal "Please provide an argument using the following format: username/repository"
    main "$*"
fi
